### ISSUE TITLE
COMPROMISOS Y EJECUCIONES: Documentos

### ISSUE THREAD

**Issue by jmff92** [jmff92/SigulabTest#19]
Según el documento elegido en lista desplegable del compromiso, aparecerá no modificable en documento de ejecución:

COMPROMISO -> EJECUCIÓN
Orden de compra -> Informe de Recepción
Orden de Servicio -> Conformidad de Servicio
Orden de Gasto -> Conformidad de Servicio

**Comment by alexgarbi10** [comment]
Muestra bien las opciones en Agregar Ejecución y Editar Ejecución, pero no funciona para el show...
